<?php

declare(strict_types=1);

namespace App\Services;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use JsonException;

/**
 * Shared service for resolving ROR (Research Organization Registry) identifiers
 * to organization names using the locally stored ROR data dump.
 *
 * The ROR data file is generated by the `php artisan get-ror-ids` command and
 * stored at `storage/app/private/ror/ror-affiliations.json`.
 *
 * This service is used by:
 * - AffiliationService (name resolution when storing affiliations)
 * - UploadXmlController (resolving ROR identifiers from uploaded XML)
 */
class RorLookupService
{
    /**
     * Cached map of canonical ROR URL → organization name.
     *
     * @var array<string, string>|null
     */
    private ?array $affiliationMap = null;

    /**
     * Resolve a ROR identifier to an organization name.
     *
     * @param  string  $rorId  A ROR identifier (URL or bare ID)
     * @return string|null The resolved organization name, or null if not found
     */
    public function resolve(string $rorId): ?string
    {
        $this->ensureLoaded();

        $canonical = $this->canonicalise($rorId);

        if ($canonical === null) {
            return null;
        }

        return $this->affiliationMap[$canonical] ?? null;
    }

    /**
     * Resolve a ROR identifier to a full affiliation array (name + canonical ROR URL).
     *
     * @param  string  $rorId  A ROR identifier (URL or bare ID)
     * @param  string|null  $fallbackName  Fallback name if ROR lookup fails
     * @return array{value: string, rorId: string}|null
     */
    public function resolveWithFallback(string $rorId, ?string $fallbackName = null): ?array
    {
        $canonical = $this->canonicalise($rorId);

        if ($canonical === null) {
            return null;
        }

        $resolvedName = $this->resolve($rorId);

        $label = $resolvedName
            ?? (is_string($fallbackName) && $fallbackName !== '' ? $fallbackName : $canonical);

        return [
            'value' => $label,
            'rorId' => $canonical,
        ];
    }

    /**
     * Canonicalise a ROR identifier to the standard URL format.
     *
     * Accepts various formats:
     * - Full URL: https://ror.org/04z8jg394
     * - Bare ID: 04z8jg394
     * - HTTP URL: http://ror.org/04z8jg394
     *
     * @return string|null Canonical ROR URL (e.g., "https://ror.org/04z8jg394") or null
     */
    public function canonicalise(string $identifier): ?string
    {
        $trimmed = trim($identifier);

        if ($trimmed === '') {
            return null;
        }

        // If already a full URL with ror.org host, extract and normalize
        if (preg_match('#^https?://ror\.org/(.+)$#i', $trimmed, $matches)) {
            $rorId = trim($matches[1]);

            return $rorId !== '' ? 'https://ror.org/' . Str::lower($rorId) : null;
        }

        // If it looks like a URL with a non-ROR host, don't process it
        if (preg_match('#^https?://#i', $trimmed)) {
            return null;
        }

        // Otherwise, treat as bare ROR ID and prepend URL
        $path = Str::lower(trim($trimmed, '/'));

        return $path !== '' ? 'https://ror.org/' . $path : null;
    }

    /**
     * Check if a string looks like a ROR URL.
     */
    public function isRorUrl(string $value): bool
    {
        return (bool) preg_match('#^https?://ror\.org/[a-z0-9]+$#i', trim($value));
    }

    /**
     * Ensure the affiliation map is loaded from disk.
     */
    private function ensureLoaded(): void
    {
        if ($this->affiliationMap !== null) {
            return;
        }

        $this->affiliationMap = [];

        try {
            $disk = Storage::disk('local');

            if (! $disk->exists('ror/ror-affiliations.json')) {
                return;
            }

            $contents = $disk->get('ror/ror-affiliations.json');

            if (! is_string($contents)) {
                return;
            }

            $decoded = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);

            if (! is_array($decoded)) {
                return;
            }

            foreach ($decoded as $entry) {
                if (! is_array($entry)) {
                    continue;
                }

                $label = isset($entry['prefLabel']) && is_string($entry['prefLabel'])
                    ? trim($entry['prefLabel'])
                    : '';
                $rorId = isset($entry['rorId']) && is_string($entry['rorId'])
                    ? $this->canonicalise($entry['rorId'])
                    : null;

                if ($label === '' || $rorId === null) {
                    continue;
                }

                $this->affiliationMap[$rorId] = $label;
            }
        } catch (JsonException) {
            // Ignore invalid file contents; map stays empty.
        }
    }
}
