import {
    Archive,
    Award,
    Book,
    BookMarked,
    BookOpen,
    Calendar,
    Clipboard,
    ClipboardList,
    Code,
    Database,
    FileBarChart,
    FileCode,
    Files,
    FileText,
    FileUp,
    FolderKanban,
    GraduationCap,
    HelpCircle,
    Image,
    type LucideIcon,
    Microscope,
    MonitorPlay,
    Music,
    Network,
    Newspaper,
    Package,
    Shield,
    Type,
    UserCheck,
    Video,
    Workflow,
    Wrench,
} from 'lucide-react';

const RESOURCE_TYPE_ICONS: Record<string, LucideIcon> = {
    Audiovisual: Video,
    Award: Award,
    Book: Book,
    BookChapter: BookOpen,
    Collection: Archive,
    ComputationalNotebook: FileCode,
    ConferencePaper: FileText,
    ConferenceProceeding: Files,
    DataPaper: FileText,
    Dataset: Database,
    Dissertation: GraduationCap,
    Event: Calendar,
    Image: Image,
    InteractiveResource: MonitorPlay,
    Instrument: Microscope,
    Journal: BookMarked,
    JournalArticle: Newspaper,
    Model: Network,
    OutputManagementPlan: Clipboard,
    PeerReview: UserCheck,
    PhysicalObject: Package,
    Preprint: FileUp,
    Project: FolderKanban,
    Report: FileBarChart,
    Service: Wrench,
    Software: Code,
    Sound: Music,
    Standard: Shield,
    StudyRegistration: ClipboardList,
    Text: Type,
    Workflow: Workflow,
    Other: HelpCircle,
};

export function getResourceTypeIcon(resourceType: string): LucideIcon {
    return RESOURCE_TYPE_ICONS[resourceType] || HelpCircle;
}
